name: CI check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt testQuick scripted
      - run: cd sample/usage && sbt "show someString"
      - run: cd sample/usage-normal && sbt "show someString"
